
- 假设500条数据，20个特征，标签分为三类，实现一个三层神经网络；
- 第一层13个神经元，第二层8个，第三层是输出层
- 第一层激活函数relu,第二层是sigmoid

In [1]:
import torch
import random
import numpy as np 
from torch.utils import data
from d2l import torch as d2l
from torch import nn


In [2]:
from torch.nn import functional as F
# 确定数据
torch.random.manual_seed(420)
X=torch.rand((500,20),dtype=torch.float32)
y=torch.randint(0,3,size=(500,1),dtype=torch.float32)



In [4]:
class Moduel(nn.Module):
    def __init__(self,in_features=10,out_features=2):
        """
        in输入的特征个数
        out输出的数目
        """
        super(Moduel,self).__init__()
        self.linear1=nn.Linear(in_features,13,bias=True)
        self.linear2=nn.Linear(13,8,True)
        self.output=nn.Linear(8,out_features,True)
    def forward(self,x):
        z1=self.linear1(X)
        sigma1=torch.relu(z1)
        z2=self.linear2(sigma1)
        sigma2=torch.sigmoid(z2)
        z3=self.output(sigma2)
        sigma3=F.softmax(z3,dim=1)
        return sigma3
    





In [7]:
X.shape[1]

20

In [9]:
y.unique()

tensor([0., 1., 2.])

In [11]:

input_=X.shape[1]
output_=len(y.unique())

In [12]:
#实例化神经网络
torch.random.manual_seed(420)
net=Moduel(in_features=input_,out_features=output_)



In [14]:
net.forward(X).shape

torch.Size([500, 3])

In [15]:
net.forward(X)

tensor([[0.4140, 0.3496, 0.2365],
        [0.4210, 0.3454, 0.2336],
        [0.4011, 0.3635, 0.2355],
        ...,
        [0.4196, 0.3452, 0.2352],
        [0.4153, 0.3455, 0.2392],
        [0.4153, 0.3442, 0.2405]], grad_fn=<SoftmaxBackward0>)

In [17]:
net.linear1.weight.shape

torch.Size([13, 20])

In [18]:
net.linear2.weight.shape

torch.Size([8, 13])

In [19]:
net.output.weight.shape

torch.Size([3, 8])

In [20]:
net.training #是否需要用于训练

True

In [ ]:
#net.cuda() #是否转移到GPU上来运行
net.cpu()

In [ ]:
# net.apply()
# 对神经网络中的所有的对象执行同样的操作

In [23]:
net.parameters()

<generator object Module.parameters at 0x15088ec80>

In [29]:
for param in net.parameters():
    print(f'{param}\n')

Parameter containing:
tensor([[ 1.3656e-01, -1.3459e-01,  2.1281e-01, -1.7763e-01, -6.8218e-02,
         -1.5410e-01,  1.7245e-01,  8.3885e-02, -1.1153e-01, -1.7294e-01,
         -1.2947e-01, -4.3138e-02, -1.1413e-01,  1.6295e-01, -9.4082e-02,
         -1.4629e-01, -6.8982e-02, -2.1836e-01, -1.0859e-01, -1.2199e-01],
        [ 4.8127e-02,  1.8186e-01,  2.4149e-02, -1.3032e-01,  9.2056e-02,
         -9.5202e-02, -1.0584e-01, -4.2852e-02, -1.1669e-01,  2.4581e-02,
          1.8152e-01,  3.0500e-02,  1.3506e-01, -1.9425e-01, -1.7591e-01,
         -2.9751e-02,  2.0485e-04,  1.3957e-01, -1.9666e-01,  9.3293e-02],
        [-1.9192e-01,  3.6070e-02,  1.4778e-01,  3.0845e-02,  7.1393e-02,
          1.4217e-01,  2.2122e-01, -1.4032e-01,  7.3255e-02,  1.8409e-01,
          1.2716e-01, -2.0253e-01, -1.5509e-01, -2.1899e-01,  9.8980e-02,
          2.2123e-01, -2.1659e-01,  1.7880e-01, -2.0922e-01, -2.7275e-02],
        [ 1.8144e-01, -3.5166e-02,  2.4801e-02,  1.6299e-01, -1.8755e-01,
          5.6